import React from 'react'
import ExpandableTextComponent from './ExpandableTextComponent'
const Lesson12_Expandable = () => {
  return (
    <div>
        <ExpandableTextComponent maxChars={80}>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Blanditiis tenetur, doloremque laudantium laborum nesciunt veritatis molestias exercitationem voluptas aliquid voluptatibus distinctio maiores, dignissimos tempore dolore. Vitae aliquid voluptas voluptatum omnis aut nisi, sunt recusandae laboriosam quis vero labore similique earum veniam consequuntur natus rem perferendis! Tempora omnis aliquam impedit officia similique quasi sequi et harum recusandae delectus quo nesciunt veritatis eveniet, sint facere voluptatibus! Tempora blanditiis amet, ullam pariatur perspiciatis voluptates corrupti architecto veritatis temporibus dolorem labore obcaecati nemo alias harum dolore mollitia neque magni sed nihil at nam repudiandae reprehenderit! Inventore enim id est optio laborum sed quam ea error eaque quod soluta odio quasi voluptatibus autem explicabo, architecto placeat, mollitia, tenetur vero sit debitis cupiditate! Totam quidem cumque quisquam reprehenderit harum. Expedita repudiandae eum natus sapiente, nobis quo id placeat nesciunt. Reprehenderit consequuntur aliquam mollitia, aspernatur repellat nisi aliquid temporibus doloribus sapiente ipsa, accusamus sed nam id, sint maxime tenetur est quaerat recusandae vel? Reiciendis cum dolores rem magnam corrupti iste similique tempore perferendis nam sapiente magni voluptates, recusandae reprehenderit repellat ullam inventore cupiditate eligendi. Possimus quas dignissimos aspernatur incidunt atque totam, quis reprehenderit vitae dolorem illum suscipit repellendus sunt nesciunt doloremque odio placeat! Sint praesentium nesciunt quis voluptatum magnam suscipit sunt, officia laudantium reiciendis! Ducimus, eveniet dolore. Iusto, numquam cupiditate reiciendis qui ipsum quasi. Ex alias unde nostrum quis, magni, ipsum omnis earum, harum nam exercitationem eos debitis quaerat accusantium. Illum obcaecati, architecto nisi quisquam rem, accusantium ipsum odio porro debitis quo aliquid consequatur minima voluptate. Natus dolorem vitae magnam veritatis magni incidunt voluptatem neque odio voluptas, provident perspiciatis, ad consequatur alias hic eveniet modi obcaecati, sequi voluptatibus aspernatur minus quia atque possimus. Dicta dolorem dolorum necessitatibus molestiae ipsum ullam officiis nemo, quas quasi earum voluptas modi velit et delectus beatae libero! Adipisci culpa qui cupiditate eaque iste fugit voluptas, maiores officia molestiae, animi ducimus reprehenderit laboriosam placeat sed. Doloremque repudiandae facilis mollitia assumenda aliquam officiis voluptate vero ipsam quisquam. Recusandae eveniet numquam atque asperiores delectus voluptate nesciunt quam, doloribus magnam tempora! Repudiandae tenetur laboriosam nobis, maxime assumenda, enim, quisquam dicta doloremque quae modi tempora nulla sint.
        </ExpandableTextComponent>
    </div>
  )
}

export default Lesson12_Expandable
